import Head from 'next/head'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import styles from '../styles/slug.module.css'


export default function Post(data) {

    const post = data.post;

    return (
        <div className={styles.container}>
            <Head>
                <title>Next.js - wordpress</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <h1 className={styles.title}>{post.title}</h1>
                <div className={styles.content} dangerouslySetInnerHTML={{ __html: post.content }}></div>
            </div>
        </div>
    )

}


export async function getStaticProps(context) {

    const response = await client.query({
        query: gql`
        query SinglePost($id: ID!, $idType: PostIdType!) {
            post(id: $id, idType: $idType) {
                title
                slug
                content
            }
        }
        `,
        variables: {
            id: context.params.slug,
            idType: 'SLUG'
        }
    });

    return {
        props: {
            post: response.data.post
        },
    };

}

export async function getStaticPaths() {

    const response = await client.query({
        query: gql`
            query AllPostsQuery {
                posts {
                    nodes {
                        slug
                        content
                        title
                    }
                }
            }
        `,
    });

    const posts = response.data.posts.nodes;

    const paths = posts.map((post) => ({
        params: { slug: post.slug },
    }))

    return {
        paths,
        fallback: false
    }
}